function dw=CalcDynamicWindow(x,config)
    dt = config.dt;
    % Compute DyamicWindow from model and current state
    % Window by vehicle model
    Vs=[config.min_speed,...
        config.max_speed,...
        config.min_yaw_rate,...
        config.max_yaw_rate];

    % Window by motion model
    Vd=[x(4)-config.max_accel*dt,...
        x(4)+config.max_accel*dt,...
        x(5)-config.max_delta_yaw_rate*dt,...
        x(5)+config.max_delta_yaw_rate*dt];

    % Final Dynamic Window Computation
    %[vmin,vmax,ωmin,ωmax]
    dw = [max(Vs(1), Vd(1)), min(Vs(2), Vd(2)),...
          max(Vs(3), Vd(3)), min(Vs(4), Vd(4))];
end